landing-page/project/account/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
# from django.contrib.auth.views import login, logout
from django.views.generic.base import TemplateView
from django.contrib.auth import views
from . import views
from django.contrib.auth import views as auth_views

 

from django.contrib.auth.views import PasswordResetView

from django.urls import path


app_name = "account"
urlpatterns = [



	path('login/', views.login_page, name='login'),
	path('logout/', views.logout_page, name='logout'),	
	path('register/', views.register, name='register'),
	path('register_success/', views.registration_success, name='registration_success'),




] 

landing-page/project/index/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views
# from mysite.core import views as core_views
app_name='home'
urlpatterns = [
    path('', views.home, name="home" ),
	path('register-seeker/', views.register_seeker, name="register_seeker" ),
	path('register-poster/', views.register_poster, name="register_poster" ),
	path('post/', views.post, name="post" ),
	path('login/', views.login_page, name="login" ),
	path('loginpage/', views.login_view, name="login_view" ),
	path('logout/', views.logout_page, name="logout_page" ),
	path('filter/', views.search_field, name="search_field" ),
	# url(r'^$', core_views.home, name='home'),
	# url(r'^login/$', auth_views.login, name='login'),
	# path('login/', views.login, name="login" ),
	# url(r'^login/$', auth_views.login, name='login'),
	# url(r'^logout/$', auth_views.logout, name='logout'),

]

landing-page/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('index.urls')),
    path("account/", include('account.urls')),
    path("oauth/", include('social_django.urls', namespace='social')),
    # url(r'^oauth/', include('social_django.urls', namespace='social')),
]

landing-page/project/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>BUDESCODE</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="fonts/icomoon/style.css">

 <!--    <link rel="stylesheet" href="css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
   
  </head>
    <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
   
    
    <header class="site-navbar py-4 js-sticky-header site-navbar-target" role="banner">
      
      <div class="container-fluid">
        <div class="d-flex align-items-center">
          <div class="site-logo mr-auto w-25"><a href="{% url 'home:home' %}">BUDESCODE</a></div>

          <div class="mx-auto text-center">
            <nav class="site-navigation position-relative text-right" role="navigation">
              <ul class="site-menu main-menu js-clone-nav mx-auto d-none d-lg-block  m-0 p-0">
                <li><a href="{% url 'home:home' %}" class="nav-link">Home</a></li>
                <li><a href="" class="nav-link">{{request.user.username}}</a></li>
                 {% if request.user.is_authenticated %}
                  <li><a href="{% url 'home:logout_page' %}" class="nav-link">Log out</a></li>
                  {% endif %}
 <!--                <li><a href="#programs-section" class="nav-link">Programs</a></li>
                <li><a href="#teachers-section" class="nav-link">Teachers</a></li> -->
              </ul>
            </nav>
          </div>

          <div class="ml-auto w-25">
            <nav class="site-navigation position-relative text-right" role="navigation">
              <ul class="site-menu main-menu site-menu-dark js-clone-nav mr-auto d-none d-lg-block m-0 p-0">
              <li class="cta"><a href="{% url 'account:login' %}" class="nav-link"><span>Login</span></a></li>
              <li class="cta"><a href="{% url 'account:register' %}" class="nav-link"><span>Register</span></a></li>
              
             
  

            
              </ul>
            
            </nav>
            <a href="#" class="d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black float-right"><span class="icon-menu h3"></span></a>
          </div>
        </div>
      </div>
      
    </header>
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
{% block body %}
{% endblock %}

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
  <script src="{% static 'js/jquery.sticky.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
   
  </body>
</html>

landing-page/project/templates/filter.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}



    <div class="intro-section" id="home-section">
      
    <div class="slide-1" style="background-image: url('../static/images/hero_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12">
              <div class="row align-items-center">
                <div class="col-lg-12 mb-4">
               {{qs}} 	


</div>  <!-- col-lg-5 -->
 






                </div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
{% endblock %}

landing-page/project/templates/first_name.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}



    <div class="intro-section" id="home-section">
      
    <div class="slide-1" style="background-image: url('../static/images/hero_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12">
              <div class="row align-items-center">
                <div class="col-lg-12 mb-4">
                	

<center>
<h1>Posted Successful</h1>
        <center><h2 style="font-family: 'black_jackregular'; color: white;"><i class="fa fa-paper-plane" aria-hidden="true" style="color: orange"></i>&nbsp;{{username}} posted as {{request.user.first_name}}</h2></center><br>
      
        <p>
         <center><p>Click on the button below to Post again</p></center>
<a href="{% url 'home:post' %}"><button type="button" class="btn btn-md btn-block" style="background-color: rgb(79, 69, 227); color: white;"><i class="fa fa-paper-plane-o" aria-hidden="true"></i>&nbsp;Post</button></a>
    
     </p>
     </center>
</div>  <!-- col-lg-5 -->
 






                </div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
{% endblock %}

landing-page/project/templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}



  


    <div class="intro-section" id="home-section">
      
    <div class="slide-1" style="background-image: url('../static/images/hero_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12">
              <div class="row align-items-center">
                <div class="col-lg-6 mb-4">
                {% if request.user.is_authenticated %}
                  <h1  data-aos="fade-up" data-aos-delay="100">You're logged in as a {{category}}</h1>

                 

                  <p class="mb-4"  data-aos="fade-up" data-aos-delay="200">Click the button below to post</p>
                  <p data-aos="fade-up" data-aos-delay="300"><a href="{% url 'home:post' %}" class="btn btn-primary py-3 px-5 btn-pill">Post</a></p>
                   {% else %}

                  <h1  data-aos="fade-up" data-aos-delay="100">Welcome...</h1>

                 

                  <p class="mb-4"  data-aos="fade-up" data-aos-delay="200">Login to post</p>
                  
                   {% endif %}


                </div>

    <div class="col-lg-5 ml-auto" data-aos="fade-up" data-aos-delay="500">

    {% if request.user.is_authenticated %}

<form method="post" enctype="multipart/form-data" action="{% url 'home:search_field' %}" style="">{% csrf_token %}

 {% if request.user.first_name == "Poster" %}
    <div class="form-row">
      <div class="form-group">
        <input type="text" name="seeker">
      </div>
    
    <div class="form-group">
         <input type="submit" name="" value="Search Seeker">
      </div>
  
    
    </div>
{% else %}

    <div class="form-row">
      <div class="form-group">
        <input type="text" name="poster">
      </div>
    
    <div class="form-group">
         <input type="submit" name="" value="Search Poster">
      </div>
  
    
    </div>

    {% endif %}

  </form>

    {% else %}
               




  <!-- Tab panes -->
  <div class="tab-content">
    <div id="home" class="container tab-pane active"><br>
    <p> <h4 style="color: white;">Sign up as a poster or seeker</h4></p>
      
                  <form action="{% url 'account:register' %}" method="post" class="form-box"> {% csrf_token %}
                    <h3 class="h4 text-black mb-4">Sign up as a seeker</h3>
                    <div class="form-group">
                      {{ form.username|as_crispy_field }}
                    </div>
                    <div class="form-group">
                      {{ form.email|as_crispy_field }}
                    </div>
                    <div class="form-group mb-4">
                      {{ form.password|as_crispy_field }}
                    </div>
                    <div class="form-group mb-4">
                      {{ form.category|as_crispy_field }}
                    </div>
                    <div class="form-group">
                      <input type="submit" class="btn btn-primary btn-pill" value="Sign up">
                    </div>
                  </form>
    </div>




          <div class="p-t-27" style="color: white;"> 
          <span><b>Login with</b></span> 
            <a href="{% url 'account:login' %}" class="">
              <i class="fa fa-user"></i>
            </a>
            <a href="{% url 'social:begin' 'facebook' %}" class="">
              <i class="fa fa-facebook"></i>
            </a>
            <a href="#" class="">
              <i class="fa fa-linkedin"></i>
            </a>
          <a href="{% url 'social:begin' 'github' %}" class="">
            <i class="fa fa-github"></i>
          </a>


          </div>

  </div>

  {% endif %}
</div>  <!-- col-lg-5 -->
 






                </div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
    </div>

    



    




    


  
    
  </div> <!-- .site-wrap -->

{% endblock %}

landing-page/project/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}



    <div class="intro-section" id="home-section">
      
    <div class="slide-1" style="background-image: url('../static/images/hero_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12">
              <div class="row align-items-center">
                <div class="col-lg-6 mb-4">


                </div>

    <div class="col-lg-5 ml-auto" data-aos="fade-up" data-aos-delay="500">
               <p> <h4 style="color: white;">Sign in</h4></p>


<form method="post" action="{% url 'account:login' %}">
  {% csrf_token %}
  {{form|crispy}}


  <button type="submit" class="btn btn-primary ">Login</button> 
</form>
<br>
          <div class="p-t-27" style="color: white;"> 
          <span><b>Or Login with</b></span> 
            <a href="{% url 'social:begin' 'facebook' %}" class="">
              <i class="fa fa-facebook"></i>
            </a>
            <a href="#" class="">
              <i class="fa fa-linkedin"></i>
            </a>

        <a href="{% url 'social:begin' 'github' %}" class="">
          <i class="fa fa-github"></i>
        </a>

            <a href="#" class="">
              <i class="fa fa-google"></i>
            </a>
          </div>
  <!-- Tab panes -->

</div>  <!-- col-lg-5 -->
 






                </div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
{% endblock %}

landing-page/project/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}



    <div class="intro-section" id="home-section">
      
    <div class="slide-1" style="background-image: url('../static/images/hero_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12">
              <div class="row align-items-center">
                <div class="col-lg-12 mb-4">
<center> <h1>Logged out</h1>
 <p>You have been successfully logged out. </p>
          <div class="p-t-27" style="color: white;"> 
          <span><b> Login with</b></span> 
             <a href="{% url 'account:login' %}" class="">
              <i class="fa fa-user"></i>
            </a>
            <a href="{% url 'social:begin' 'facebook' %}" class="">
              <i class="fa fa-facebook"></i>
            </a>
            <a href="#" class="">
              <i class="fa fa-linkedin"></i>
            </a>

        <a href="{% url 'social:begin' 'github' %}" class="">
          <i class="fa fa-github"></i>
        </a>


          </div></center>

                </div>
<p><a href="{% url 'home:home' %}"> Goto homepage</a></p>

 






                </div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
{% endblock %}

landing-page/project/templates/post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<style>
  label{
    color: white;
  }
  .form-text text-muted{
    color: white;
  }
</style>


  


   
      
    <div class="slide-1" style="background-color: #353B40;" >
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12">
              <div class="row align-items-center">
 

    <div class="col-lg-12 ml-auto" data-aos="fade-up" data-aos-delay="500" style="margin-top: 80px;">
    <h5 style="color: white;">You're posting as a {{request.user.first_name}}</h5>
<form method="post" enctype="multipart/form-data" action="{% url 'home:post' %}">{% csrf_token %}


    <div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.f0|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.f1|as_crispy_field }}
      </div>
    <div class="form-group col-md-3 mb-0">
        {{ form.f2|as_crispy_field }}
      </div>
    <div class="form-group col-md-3 mb-0">
        {{ form.f3|as_crispy_field }}
      </div>
    
    </div>
   
    <div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.f4|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.f5|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.f6|as_crispy_field }}
      </div>
    <div class="form-group col-md-3 mb-0">
        {{ form.f7|as_crispy_field }}
      </div>
    </div> 
<div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.f8|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.f9|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.f10|as_crispy_field }}
      </div>
    <div class="form-group col-md-3 mb-0">
        {{ form.f11|as_crispy_field }}
      </div>
    </div> 
<div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.f12|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.f13|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.f14|as_crispy_field }}
      </div>
    <div class="form-group col-md-3 mb-0">
        {{ form.f15|as_crispy_field }}
      </div>
    </div> 


<div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.f16|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.f17|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.f18|as_crispy_field }}
      </div>
    <div class="form-group col-md-3 mb-0">
        {{ form.f19|as_crispy_field }}
      </div>
    </div> 


<div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.f20|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.f21|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.f22|as_crispy_field }}
      </div>
    <div class="form-group col-md-3 mb-0">
        {{ form.f23|as_crispy_field }}
      </div>
    </div> 
<div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.f24|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.f25|as_crispy_field }}
      </div>

    <div class="form-group col-md-3 mb-0">
        {{ form.f27|as_crispy_field }}
      </div>



      <div class="form-group col-md-3 mb-0">
        {{ form.f29|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.f30|as_crispy_field }}
      </div>

</div>




<input class="btn btn-primary" type="submit" value="Post" name="">


</form>

  <!-- Tab panes -->

</div>  <!-- col-lg-5 -->
 






                </div>
              </div>
            </div>
            
          </div>
        </div>

     
    

    



    




    


  
    
  </div> <!-- .site-wrap -->

{% endblock %}

landing-page/project/templates/post_success.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}



    <div class="intro-section" id="home-section">
      
    <div class="slide-1" style="background-image: url('../static/images/hero_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12">
              <div class="row align-items-center">
                <div class="col-lg-12 mb-4">
                	

<center>
<h1>Posted Successful</h1>
        <center><h2 style="font-family: 'black_jackregular'; color: white;"><i class="fa fa-paper-plane" aria-hidden="true" style="color: orange"></i>&nbsp;{{username}} posted as {{request.user.first_name}}</h2></center><br>
      
        <p>
         <center><p>Click on the button below to Post again</p></center>
<a href="{% url 'home:post' %}"><button type="button" class="btn btn-md btn-block" style="background-color: rgb(79, 69, 227); color: white;"><i class="fa fa-paper-plane-o" aria-hidden="true"></i>&nbsp;Post</button></a>
    
     </p>
     </center>
</div>  <!-- col-lg-5 -->
 






                </div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
{% endblock %}

landing-page/project/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}



    <div class="intro-section" id="home-section">
      
    <div class="slide-1" style="background-image: url('../static/images/hero_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12">
              <div class="row align-items-center">
                <div class="col-lg-6 mb-4">
                	

                </div>

    <div class="col-lg-5 ml-auto" data-aos="fade-up" data-aos-delay="500">
               <p> <h4 style="color: white;">Register</h4></p>


<form method="post">
<h1>{{msg}}</h1>
<form method="post" enctype="multipart/form-data" action="{% url 'account:register' %}">{% csrf_token %}
{{form|crispy}}
<input class="btn btn-primary" type="submit" value="Register" name="">


</form>
</form>


</div>  <!-- col-lg-5 -->
 






                </div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
{% endblock %}

landing-page/project/templates/registration_success.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}



    <div class="intro-section" id="home-section">
      
    <div class="slide-1" style="background-image: url('../static/images/hero_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12">
              <div class="row align-items-center">
                <div class="col-lg-12 mb-4">
                	

<center>
<h1>Registration Successful</h1>
        <center><h2 style="font-family: 'black_jackregular'; color: white;"><i class="fa fa-paper-plane" aria-hidden="true" style="color: orange"></i>&nbsp;{{username}} Registered as {{first_name}}</h2></center><br>
      
        <p>
         <center><p>Click on the button below to login</p></center>
<a href="{% url 'account:login' %}"><button type="button" class="btn btn-md btn-block" style="background-color: rgb(79, 69, 227); color: white;"><i class="fa fa-paper-plane-o" aria-hidden="true"></i>&nbsp;Login</button></a>
    
     </p>
     </center>
</div>  <!-- col-lg-5 -->
 






                </div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
{% endblock %}